@Library(['sym-pipeline@main']) _

import com.symphony.cicd.SymphonyCICDUtils

def cicdUtils = new SymphonyCICDUtils()
def isPullRequest = cicdUtils.isPullRequest()

String projectOrg = "SymphonyOSF"
String projectRepo = "kubedock"
String containerRepository = "us-east4-docker.pkg.dev/sym-prod-mr-tools-01/kubedock-docker-us-east4"

podTemplate(
  cloud: "kubernetes-build-cicd-jenkins-agent",
  yaml: readTrusted('jenkins/podTemplate.yaml'),
  yamlMergeStrategy: merge()
) {

node(POD_LABEL) {
  properties([disableConcurrentBuilds(abortPrevious: true)])

  stage('Setup Check') {
    echo sh(script: 'env|sort', returnStdout: true)
    sh "gcloud auth configure-docker us-east4-docker.pkg.dev"
  }

  stage("checkout") {        
    gitHash = gitCheckout()
    version = "${BRANCH_NAME}.${BUILD_ID}.${gitHash}".toLowerCase()
    addArtifactLinkToDescription("${projectRepo}:${version}", "https://console.cloud.google.com/artifacts/generic/sym-prod-mr-tools-01/us-east4/sym-generic/${projectRepo}/${version}")
  }

  stage("Checkout") {
    prGitHash = gitCheckout()
    echo "PR Git hash: ${prGitHash}"

    shortGitHash = cicdUtils.getShortGitHash()
    semantic_version = getCurrentPomProperty("revision")
    now = getDate()
    branch = BRANCH_NAME.replaceAll(/[\.-]/, "_")

    imageTag = "${semantic_version}-${BUILD_NUMBER}-${branch}-${now}-${shortGitHash}"
    if (isPullRequest) {
      withCredentials([usernamePassword(credentialsId: 'symphonyjenkinsauto-sbe', usernameVariable: 'USERNAME', passwordVariable: 'GH_TOKEN')]) {
        def comment = "ImagesTag: ${imageTag}"

        sh """
        curl -H "Authorization: token $GH_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${projectOrg}/${projectRepo}/issues/${env.CHANGE_ID}/comments \
              -d '{\"body\": \"$comment\"}'
        """
      }
    }
    parallel "ImagesTag: ${imageTag}": {}
    currentBuild.description = "<strong>${imageTag}</strong><br>"
  }

  stage("build") {
    container("ubuntu") {
      withCredentials([
              usernamePassword(credentialsId: 'repo-symphony', usernameVariable: 'ARTIFACTORY_USER', passwordVariable: 'ARTIFACTORY_TOKEN')
      ]) {
        sh """
          export "GOPROXY=https://\${ARTIFACTORY_USER}:\${ARTIFACTORY_TOKEN}@repo.symphony.com/artifactory/api/go/go-virtual-mirror"
          mv packaging/debian ./
          echo 1.0 > debian/source/format
          sed -i 's/golang-go/golang-1.23-go/g' debian/control
          sed -i '/GOPROXY/d' debian/rules
          dpkg-buildpackage -us -uc -rfakeroot || true
        """
      }
    }
  }

  stage("publish") {
    sh """
      gcloud artifacts generic upload \
        --project=sym-prod-mr-tools-01 \
        --source="../apt-transport-artifact-registry_20210304.00-g1_amd64.deb" \
        --package=${projectRepo} \
        --version=${version} \
        --location=us-east4 \
        --repository=sym-generic
    """
  }
}}

def addArtifactLinkToDescription(name, url) {
  String artifactLink = "<a href='${url}'>${name}</a><br>"
  if (currentBuild.description) {
    currentBuild.description = currentBuild.description + artifactLink
  } else {
    currentBuild.description = artifactLink
  }
}